# Generated by Django 4.2.3 on 2023-07-20 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_voter_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voter',
        ),
    ]
